2025-02-28 19:02:48,741:ERROR:Error processing product: Invalid control character at: line 8 column 44 (char 202)
Traceback (most recent call last):
  File "C:\Users\user_\Downloads\Data&Data\Data&Data - PriceAnalysis Challenge\Data-Data-Challenge\src\scraper\utils.py", line 51, in extract_product_info
    data_tracking = json.loads(data_tracking.replace("&quot;", '"'))
  File "C:\Users\user_\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user_\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user_\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 8 column 44 (char 202)
2025-02-28 19:02:48,757:ERROR:Error in data_extraction for Japan: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "C:\Users\user_\Downloads\Data&Data\Data&Data - PriceAnalysis Challenge\Data-Data-Challenge\src\scraper\utils.py", line 131, in extract
    product_info["country"] = country
TypeError: 'NoneType' object does not support item assignment
2025-02-28 19:03:05,375:ERROR:clean_data: Removed 4 rows with missing values
NoneType: None
