2025-02-28 17:50:10,636:ERROR:clean_data: Removed 4 rows with missing values
NoneType: None
2025-02-28 17:50:10,642:ERROR:transform_data: 147 missing currency mappings
NoneType: None
2025-02-28 17:50:10,643:ERROR:transform_data: Currency conversion failed - name 'currencies_code' is not defined
Traceback (most recent call last):
  File "C:\Users\user_\Downloads\Data&Data\Data&Data - PriceAnalysis Challenge\Data-Data-Challenge\src\scraper\utils.py", line 309, in transform_data
    df[f"price_{target_currency}"] = df.apply(
  File "C:\Users\user_\Downloads\Data&Data\Data&Data - PriceAnalysis Challenge\Data-Data-Challenge\virtualenv\lib\site-packages\pandas\core\frame.py", line 9423, in apply
    return op.apply().__finalize__(self, method="apply")
  File "C:\Users\user_\Downloads\Data&Data\Data&Data - PriceAnalysis Challenge\Data-Data-Challenge\virtualenv\lib\site-packages\pandas\core\apply.py", line 678, in apply
    return self.apply_standard()
  File "C:\Users\user_\Downloads\Data&Data\Data&Data - PriceAnalysis Challenge\Data-Data-Challenge\virtualenv\lib\site-packages\pandas\core\apply.py", line 798, in apply_standard
    results, res_index = self.apply_series_generator()
  File "C:\Users\user_\Downloads\Data&Data\Data&Data - PriceAnalysis Challenge\Data-Data-Challenge\virtualenv\lib\site-packages\pandas\core\apply.py", line 814, in apply_series_generator
    results[i] = self.f(v)
  File "C:\Users\user_\Downloads\Data&Data\Data&Data - PriceAnalysis Challenge\Data-Data-Challenge\src\scraper\utils.py", line 310, in <lambda>
    lambda row: row["price"] * get_exchange_rate(row["currency_code"], target_currency) if row["currency_code"] in currencies_code.values() else None,
NameError: name 'currencies_code' is not defined
